In [1]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [2]:
# Load Dataset
df = pd.read_csv("student_scores.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
print("----- First 5 Rows -----")
df.head()

----- First 5 Rows -----

,Name,College,Course,Year,Math,Science,English
0,Gowthaami S M,KCG College of Technology,AI & DS,3,85,90,88
1,Jeevasri S,KCG College of Technology,AI & DS,3,78,82,80
2,Sathish kumar S,KCG College of Technology,AI & DS,3,92,89,95
3,Sifani J,KCG College of Technology,AI & DS,3,88,91,87
4,Pranathi P,KCG College of Technology,AI & DS,3,95,94,93

In [4]:
print("----- Last 5 Rows -----")
df.tail()

----- Last 5 Rows -----

,Name,College,Course,Year,Math,Science,English
0,Gowthaami S M,KCG College of Technology,AI & DS,3,85,90,88
1,Jeevasri S,KCG College of Technology,AI & DS,3,78,82,80
2,Sathish kumar S,KCG College of Technology,AI & DS,3,92,89,95
3,Sifani J,KCG College of Technology,AI & DS,3,88,91,87
4,Pranathi P,KCG College of Technology,AI & DS,3,95,94,93

In [5]:
print("Rows and Columns:")
print(df.shape)

Rows and Columns:
(5, 7)

In [6]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['Name', 'College', 'Course', 'Year', 'Math', 'Science', 'English'], dtype='object')

In [7]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   College  5 non-null      object
 2   Course   5 non-null      object
 3   Year     5 non-null      int64
 4   Math     5 non-null      int64
 5   Science  5 non-null      int64
 6   English  5 non-null      int64
dtypes: int64(4), object(3)
memory usage: 412.0+ bytes

In [8]:
print("Statistical Summary:")
df.describe()

Statistical Summary:

       Year       Math    Science   English
count   5.0   5.000000   5.000000   5.00000
mean    3.0  87.600000  89.200000  88.60000
std     0.0   6.580274   4.438468   5.85662
min     3.0  78.000000  82.000000  80.00000
25%     3.0  85.000000  89.000000  87.00000
50%     3.0  88.000000  90.000000  88.00000
75%     3.0  92.000000  91.000000  93.00000
max     3.0  95.000000  94.000000  95.00000

In [9]:
print("NumPy and Pandas learning completed!")
print("Dataset loaded successfully.")

NumPy and Pandas learning completed!
Dataset loaded successfully.