In [2]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [4]:
df = pd.read_csv("student_scores_dirty.csv")
print("Original Dataset")
df

Original Dataset

,Name,College,Course,Year,Math,Science,English
0,Gowthaami S M,KCG College of Technology,AI & DS,3,85,90.0,88.0
1,Rahul,KCG College of Technology,AI & DS,3,78,82.0,80.0
2,Priya,KCG College of Technology,AI & DS,3,92,NaN,95.0
3,Arjun,KCG College of Technology,AI & DS,3,88,91.0,NaN
4,Sneha,KCG College of Technology,AI & DS,3,95,94.0,93.0
5,Rahul,KCG College of Technology,AI & DS,3,78,82.0,80.0

In [5]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Name       0
College    0
Course     0
Year       0
Math       0
Science    1
English    1
dtype: int64

In [6]:
df["Science"] = df["Science"].fillna(df["Science"].mean())
df["English"] = df["English"].fillna(df["English"].mean())

print("Missing values handled successfully.")

Missing values handled successfully.

In [7]:
df = df.drop_duplicates()
print("Duplicates removed successfully.")

Duplicates removed successfully.

In [8]:
print("Dataset Information")
df.info()

Dataset Information
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   College  5 non-null      object
 2   Course   5 non-null      object
 3   Year     5 non-null      int64
 4   Math     5 non-null      int64
 5   Science  5 non-null      float64
 6   English  5 non-null      float64
dtypes: float64(2), int64(2), object(3)
memory usage: 320.0+ bytes

In [9]:
print("Dataset Statistics")
df.describe()

Dataset Statistics

       Year       Math    Science    English
count   5.0   5.000000   5.000000   5.000000
mean    3.0  87.600000  88.960000  88.640000
std     0.0   6.580274   4.484194   5.843629
min     3.0  78.000000  82.000000  80.000000
25%     3.0  85.000000  87.800000  87.200000
50%     3.0  88.000000  90.000000  88.000000
75%     3.0  92.000000  91.000000  93.000000
max     3.0  95.000000  94.000000  95.000000

In [10]:
print("Clean Dataset")
df

Clean Dataset

,Name,College,Course,Year,Math,Science,English
0,Gowthaami S M,KCG College of Technology,AI & DS,3,85,90.0,88.0
1,Rahul,KCG College of Technology,AI & DS,3,78,82.0,80.0
2,Priya,KCG College of Technology,AI & DS,3,92,87.8,95.0
3,Arjun,KCG College of Technology,AI & DS,3,88,91.0,87.2
4,Sneha,KCG College of Technology,AI & DS,3,95,94.0,93.0

In [11]:
df.to_csv("student_scores_clean.csv", index=False)
print("Clean dataset prepared.")

Clean dataset prepared.